export const SHELL_CACHE = "homecare-shell-v2";

export const SHELL_PRECACHE = [
  "/",
  "/index.html",
  "/manifest.webmanifest",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/icons/apple-touch-icon.png",
];

export function serviceWorkerSource(config, version) {
  return `/* Generated by scripts/write-sw.mjs. Do not edit. */
importScripts("https://www.gstatic.com/firebasejs/${version}/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/${version}/firebase-messaging-compat.js");

try {
  firebase.initializeApp(${JSON.stringify(config)});
  const messaging = firebase.messaging();
  messaging.onBackgroundMessage((payload) => {
    const data = payload.data || {};
    if (payload.notification) return;
    const title = data.title || "HammondCare";
    const body = data.body || "";
    self.registration.showNotification(title, {
      body,
      icon: "/icons/icon-192.png",
      badge: "/icons/icon-192.png",
      silent: false,
      requireInteraction: data.type === "medication",
      data,
    });
  });
} catch (error) {
  // Push setup must not stop the app shell from caching.
}

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const data = event.notification.data || {};
  let url = "/";
  if (data.type === "medication") {
    url = "/?view=home&med=" + encodeURIComponent(data.medicationId || "") + "&time=" + encodeURIComponent(data.scheduledTime || "");
  } else if (data.type === "message" && data.threadId) {
    url = "/?view=messages&thread=" + encodeURIComponent(data.threadId);
  } else if (data.type === "swap") {
    url = "/?view=calendar";
  }
  event.waitUntil(
    self.clients.matchAll({ type: "window", includeUncontrolled: true }).then((windows) => {
      for (const client of windows) {
        if ("focus" in client) {
          if (client.navigate) client.navigate(url);
          return client.focus();
        }
      }
      return self.clients.openWindow(url);
    }),
  );
});

const SHELL_CACHE = ${JSON.stringify(SHELL_CACHE)};
const SHELL_PRECACHE = ${JSON.stringify(SHELL_PRECACHE)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(SHELL_CACHE);
      await Promise.all(SHELL_PRECACHE.map((url) => cache.add(url).catch(() => undefined)));
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(keys.filter((key) => key !== SHELL_CACHE).map((key) => caches.delete(key)));
      await self.clients.claim();
    })(),
  );
});

async function networkFirst(request) {
  const cache = await caches.open(SHELL_CACHE);
  try {
    const response = await fetch(request);
    if (response && response.ok) {
      try {
        const copy = response.clone();
        if (request.mode === "navigate") await cache.put("/index.html", copy);
        else await cache.put(request, copy);
      } catch (error) {
        // A cache write must not hide a response the network already returned.
      }
    }
    return response;
  } catch (error) {
    const cached = await caches.match(request);
    if (cached) return cached;
    if (request.mode === "navigate") {
      const shell = (await caches.match("/index.html")) || (await caches.match("/"));
      if (shell) return shell;
    }
    return Response.error();
  }
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  let url;
  try {
    url = new URL(request.url);
  } catch (error) {
    return;
  }
  if (url.origin !== self.location.origin) return;
  event.respondWith(networkFirst(request));
});
`;
}
