import { existsSync, readFileSync, writeFileSync } from "node:fs";

const mode = process.argv[2] || "development";

function loadEnv(file) {
  if (!existsSync(file)) return;
  for (const line of readFileSync(file, "utf8").split("\n")) {
    const match = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (!match || process.env[match[1]]) continue;
    process.env[match[1]] = match[2].replace(/^["']|["']$/g, "");
  }
}

loadEnv(".env");
loadEnv(`.env.${mode}`);
loadEnv(".env.local");

let version = "11.9.1";
if (existsSync("node_modules/firebase/package.json")) {
  version = JSON.parse(readFileSync("node_modules/firebase/package.json", "utf8")).version;
}

const config = {
  apiKey: process.env.VITE_FIREBASE_API_KEY || "",
  authDomain: process.env.VITE_FIREBASE_AUTH_DOMAIN || "",
  projectId: process.env.VITE_FIREBASE_PROJECT_ID || "",
  storageBucket: process.env.VITE_FIREBASE_STORAGE_BUCKET || "",
  messagingSenderId: process.env.VITE_FIREBASE_MESSAGING_SENDER_ID || "",
  appId: process.env.VITE_FIREBASE_APP_ID || "",
};

const source = `/* Generated by scripts/write-sw.mjs. Do not edit. */
importScripts("https://www.gstatic.com/firebasejs/${version}/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/${version}/firebase-messaging-compat.js");

firebase.initializeApp(${JSON.stringify(config)});
const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  const data = payload.data || {};
  if (payload.notification) return;
  const title = data.title || "HomeCare";
  const body = data.body || "";
  self.registration.showNotification(title, {
    body,
    icon: "/icons/icon-192.png",
    badge: "/icons/icon-192.png",
    silent: false,
    requireInteraction: data.type === "medication",
    data,
  });
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const data = event.notification.data || {};
  let url = "/";
  if (data.type === "medication") {
    url = "/?view=home&med=" + encodeURIComponent(data.medicationId || "") + "&time=" + encodeURIComponent(data.scheduledTime || "");
  } else if (data.type === "message" && data.threadId) {
    url = "/?view=messages&thread=" + encodeURIComponent(data.threadId);
  } else if (data.type === "swap") {
    url = "/?view=calendar";
  }
  event.waitUntil(
    self.clients.matchAll({ type: "window", includeUncontrolled: true }).then((windows) => {
      for (const client of windows) {
        if ("focus" in client) {
          if (client.navigate) client.navigate(url);
          return client.focus();
        }
      }
      return self.clients.openWindow(url);
    }),
  );
});

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open("homecare-v1").then((cache) => cache.addAll(["/", "/manifest.webmanifest"])));
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(self.clients.claim());
});

self.addEventListener("fetch", (event) => {
  if (event.request.mode !== "navigate") return;
  event.respondWith(fetch(event.request).catch(() => caches.match("/index.html")));
});
`;

writeFileSync("public/sw.js", source);
console.log(`Wrote public/sw.js for ${mode}`);
